app:
  build: ./app
  volumes:
    - ./..:/var/www/html/public
  tty: true

db:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
  volumes:
    - ./mysql/data:/var/lib/mysql

php:
  build: ./php
  links:
    - db
  volumes_from:
    - app

nginx:
  build: ./nginx
  ports:
    - 80:80
  links:
    - php
  volumes_from:
    - app
  volumes:
    - ./nginx:/etc/nginx/conf.d
