app:
  build: ./app
  volumes:
    - ./..:/var/www
  tty: true

db:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: root
    MYSQL_PASSWORD: root
  ports:
    - 3306:3306
  volumes:
    - ./mysql/var/lib/mysql:/var/lib/mysql

php:
  build: ./php
  links:
    - db
  volumes_from:
    - app

nginx:
  build: ./nginx
  ports:
    - 80:80
  links:
    - php
  volumes_from:
    - app
