version: '2'

services:
  app:
    build: ./app
    volumes:
      - /srv:/srv
    tty: true

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/var/lib/mysql:/var/lib/mysql
    # log_driver: none

  redis:
    image: redis

  php:
    hostname: docker-php
    build: ./php
    depends_on:
      - db
      - redis
    volumes_from:
      - app

  nginx:
    build: ./nginx
    depends_on:
      - php
    ports:
      - 80:80
    volumes_from:
      - app
    volumes:
      - ./nginx/vhosts:/etc/nginx/conf.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - 8080:80

  nodejs:
    build: ./nodejs
    depends_on:
      - db
      - redis
    ports:
      - 3000:3000
    volumes_from:
      - app
    tty: true

  sonarqube:
    image: sonarqube:latest
    ports:
      - 9000:9000

  jenkins:
    image: jenkins:latest
    ports:
      - 8090:8080
