app:
  container_name: app
  build: ./app
  volumes:
    - /srv:/srv
  tty: true

db:
  container_name: db
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
  volumes:
    - ./mysql/var/lib/mysql:/var/lib/mysql
  # log_driver: none

redis:
  container_name: redis
  image: redis

php:
  container_name: php
  hostname: docker-php
  build: ./php
  links:
    - db
    - redis
  volumes_from:
    - app

nginx:
  container_name: nginx
  build: ./nginx
  links:
    - php
  ports:
    - 80:80
  volumes_from:
    - app
  volumes:
    - ./nginx/vhosts:/etc/nginx/conf.d

phpmyadmin:
  container_name: phpmyadmin
  image: phpmyadmin/phpmyadmin
  links:
    - db
  ports:
    - 8080:80

nodejs:
  container_name: nodejs
  build: ./nodejs
  links:
    - db
    - redis
  ports:
    - 3000:3000
  volumes_from:
    - app
  tty: true

sonarqube:
  container_name: sonarqube
  image: sonarqube:latest
  ports:
    - 9000:9000

jenkins:
  container_name: jenkins
  image: jenkins:latest
  ports:
    - 8090:8080
