app:
  build: ./app
  volumes:
    - /srv:/srv
  tty: true

db:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
  volumes:
    - ./mysql/var/lib/mysql:/var/lib/mysql
  # log_driver: none

php:
  build: ./php
  links:
    - db
  volumes_from:
    - app

nginx:
  build: ./nginx
  links:
    - php
  ports:
    - 80:80
  volumes_from:
    - app
  volumes:
    - ./nginx/vhosts:/etc/nginx/conf.d

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - db
  ports:
    - 8080:80

nodejs:
  build: ./nodejs
  links:
    - db
  ports:
    - 3000:3000
  volumes_from:
    - app
  tty: true
